### ISSUE TITLE
How to use x_seq and y_seq?

### ISSUE THREAD

**Issue by XZLeo** [oleschum/radar_scenes#14]
Hi, first of all, thank you so much for publishing the dataset and providing the GUI.

I'm working on a project to improve detection on RadarScenes. I can extract and accumulate a single sensor scan as the rada_viewer does.

It is x_cc and y_cc that are used to present In the rada_viewer, right? The problem is that car keeps moving when scanning, which means each sensor scan actually has a different global coordinate. How can they be accumulated in the ego-vehicle coordinate? Only under the assumption that time interval between two sensor scans is negligible.

I don't understand this either>

x_seq and y_seq in m, the position of the detection in the global sequence-coordinate system (origin is at arbitrary start point)

Can we reconstruct a map from x_seq and y_seq like what SLAM does? Why origin is at arbitrary start point?

Thank you again.

**Comment by oleschum** [comment]
Hi,
you are right with some of your statements, but you missed some points.

Yes, the car coordinates x_cc and y_cc are used for plotting. This is easy to achieve, if only data from a single time stamp is displayed. As you rightfully stated, the origin of the car coordinate system changes during time (when the ego vehicle moves). So in principle, the car coordinates of two different time stamps cannot be compared to each other and should not be plotted in the diagram. 
However, we use a trick here: https://github.com/oleschum/radar_scenes/blob/master/radar_scenes/viewer.py#L610
We have the sequence coordinates of all detections available. These are obtained from integrating the ego-motion. Now we can use these sequence (or sometimes called global coordinates), to transform all detections that should be visualized into the SAME car coordinate system. 
So lets say you have measurements from two timestamps t1 and t2. For both timestamps you have the positions of the detections in sequence and car coordinates. But since t1!=t2, you cannot directly use car coordinates for plotting. But since you know how the ego-vehicle moved between t1 and t2, you can use this transformation matrix to work out the car coordinates of the detection measured in t2 as if they were measured in t1. The transformation happens in this function https://github.com/oleschum/radar_scenes/blob/bff2700673db921bd208d939672e8ec938983804/radar_scenes/coordinate_transformation.py#L32

You can also display the data directly in sequence coordinates and accumulate data their. Detections from static environment will lie at the same position. So yes, you could use these coordinates for SLAM.

Regarding the origin: We chose an arbitrary point, because we can. There is no need to have special origin for the sequence coordinates. All that matters is that all transformations are done with respect to this point.

**Comment by XZLeo** [comment]
Thank you for the clarification!
