### ISSUE TITLE
What is "vr_compensated" means ?

### ISSUE THREAD

**Issue by joeking11829** [oleschum/radar_scenes#16]
Hi @oleschum ,

As the document metioned: [radar_datah5](https://radar-scenes.com/dataset/structure/#radar_datah5)

Radar have two velocity column
- vr: in m/s. Radial velocity measured for this detection
- vr_compensated in m/s: Radial velocity for this detection but compensated for the ego-motion

Because I am not familiar with Radar, I have not idea why Radial Velocity need to compensate with ego-motion.

I use the **"vr"** to plot radial velocity, the **vr direction** of each radar point **is not point to radar** itself.
when I use the **"vr_compensated"** to plot radial velocity, and the **vr_compensated direction** of each radar point **is point to radar** itself

Could you explain that ?
Thanks !!

**Comment by oleschum** [comment]
Hi!
vr is the radial velocity that the radar sensor measured. But since the sensor might be moving (it moves when the car moves) and hence has its own velocity, the measured velocity vr of a detection needs to be compensated for.

Example: The sensor moves with 10m/s towards a stationary target. The sensor reports a velocity vr of -10m/s for this detection. But this measured vr is solely due to the ego-motion of the sensor. If we want to now if the measured detection is truly moving, we have to subtract the egomotion. This is then vr_compensated.

Both vr and vr_compensated point either towards the sensor or away from it (=radial direction).

**Comment by joeking11829** [comment]
> Hi! vr is the radial velocity that the radar sensor measured. But since the sensor might be moving (it moves when the car moves) and hence has its own velocity, the measured velocity vr of a detection needs to be compensated for.
> 
> Example: The sensor moves with 10m/s towards a stationary target. The sensor reports a velocity vr of -10m/s for this detection. But this measured vr is solely due to the ego-motion of the sensor. If we want to now if the measured detection is truly moving, we have to subtract the egomotion. This is then vr_compensated.
> 
> Both vr and vr_compensated point either towards the sensor or away from it (=radial direction).

@oleschum 
Got it, Thank you.
