### ISSUE TITLE
Code snippet to plot radar points onto camera?

### ISSUE THREAD

**Issue by chowkamlee81** [oleschum/radar_scenes#8]
Hi,
Do we have any snippet of code to transform radar points onto camera FOV using some transformation matirx? Kindly help

**Comment by oleschum** [comment]
Hi,
RadarScenes was meant as a "radar only" data set. The images from the _documentary_ camera are just a reference for the developers, when they look at the data. It was never planned to fuse camera and radar data with the provided data set.
So there is no transformation matrix to project the radar point cloud into the camera image. This is anyway a hard task since there is no elevation information from the radar sensors available.
