### ISSUE TITLE
Getting full 360 degree sweep

### ISSUE THREAD

**Issue by athus1990** [oleschum/radar_scenes#9]
Hello,
I am unable to understand how to group the 4 radar inputs at each timestamp.
for example in 1 sequence there are unequla number of snapshots for radar1, radar2, radar3 and radar4.
Shouldn't they have equal number with total exactly 4 X number of timestamps?

**Comment by oleschum** [comment]
Hello @athus1990,
as noted in our paper (https://arxiv.org/abs/2104.02493), the four radar sensors are not synchronized. The cycle time of the sensors varies so that two scans of the same sensor are not always spaced by the same amount of time.
So it is possible that the radar sensors fire in a pattern
sensor 1 - sensor 2 - sensor 3 - sensor 1 - sensor 4
so that the first sensor fired again before sensor 4. 
You can of course construct artificially a a group that contains the most recent data from all four sensors. Depending on what you want to do with this group, this makes sense or not.

Btw: You would anyway not get a 360° sweep since the sensors are mounted at the front of the vehicle :)

**Comment by athus1990** [comment]
Thanks a lot for the quick reply! That is very useful to know.
 I group every sequential 4 radar inputs as 1 scene and  though not exactly correct, the scene visually makes sense.
My only concern in tracking. What happens if  the object shows up in radar2 and then in radar3 (ghosting?)..Will they have correct labels or unique track ids.

**Comment by oleschum** [comment]
I am not sure what you mean with "ghosting". But if an object is visible in multiple frames, it is labeled with a consistent trackid. Detections from all radar sensors are associated to the object so that even if the object is first only visible by radar 2 and later on only visible by radar 3, then it still has the same trackid.
